version: '3.8'

services:
  php-apache:
    build: .
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge
